version: 0.2

phases:
  build:
    commands:
      - dotnet restore WebConjugacion/WebConjugacion.sln
      - dotnet build WebConjugacion/WebConjugacion.sln
      - dotnet publish WebConjugacion/WebConjugacion.sln
artifacts:
  files:
    - WebConjugacion/bin/Debug/netcoreapp3.1/publish/*