version: 0.2

phases:
  build:
    commands:
      - dotnet restore WebConjugacion/WebConjugacion.sln
      - dotnet build WebConjugacion/WebConjugacion.sln
      - npm run build --prod --prefix WebConjugacion/ClientApp/
      - dotnet publish WebConjugacion/WebConjugacion.sln -o ./aws-publish
      - chmod 777 -R ./aws-publish
artifacts:
  files:
    - ./aws-publish/*
    - ./aws-publish/ClientApp/dist/*
    - ./aws-publish/wwwroot/*

