version: 0.2

phases:
  build:
    commands:
      - dotnet restore WebConjugacion/WebConjugacion.sln
      - dotnet build WebConjugacion/WebConjugacion.sln
      - npm run build --prefix WebConjugacion/ClientApp/ 
      - dotnet publish WebConjugacion/WebConjugacion.sln
artifacts:
  files:
    - WebConjugacion/bin/Debug/netcoreapp3.1/publish/ClientApp/dist/*
    - WebConjugacion/bin/Debug/netcoreapp3.1/publish/wwwroot/*
    - WebConjugacion/bin/Debug/netcoreapp3.1/publish/*
